BS_News/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from BS_News import views as BS_views
from BS_News.urls import urlpatterns as urls
from BS_News.views import live_feed, report, archive


urlpatterns = [
    
]

Complete_BS/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy, re_path, reverse
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from Content import views as Content_views
# from Content.views import send_mail
# from BS_News import views as BS_news
# from BS_News.urls import urlpatterns as urls
from Content.urls import urlpatterns as urls
from Content import forms
from Content.views import home, homepage, policies


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', home, name='home'),
    path('homepage', homepage, name='homepage'),
    path('policies', policies, name='policies'),
    path('/', include('Content.urls')),
#    path('__debug__/', include('debug_toolbar.urls')),
    path('users/register', user_views.register, name='register'),
    path('users/profile', user_views.profile, name='profile'),
    path('login',
         auth_views.LoginView.as_view(template_name='Content/login.html'),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='Content/logout.html'),
         name='logout'),
    path("admin/password_reset/", auth_views.PasswordResetView.as_view(
        extra_context={"site_header": admin.site.site_header}
    ), name="admin_password_reset"),
    path("admin/password_reset/done/", auth_views.PasswordResetDoneView.
         as_view(extra_context={"site_header": admin.site.site_header}),
         name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.
         as_view(extra_context={"site_header": admin.site.site_header}),
         name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
        extra_context={"site_header": admin.site.site_header}),
         name="password_reset_complete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Content/urls.py
from django.urls import path, include, reverse_lazy, re_path, reverse
from users import views as user_views
from django.contrib.auth import views as auth_views
from Content.views import homepage, report_detail
from Content.views import success, NewsReportDetailView, send_mail1
from Content.views import BSReportDeleteView, BSReportUpdateView, about_BS
from Content.views import ContactCreateView, CreateReport, report_list
from Content.views import EditNewsReportView, NewsViewSet
from Content import views
from Content.models import NewsReport
from rest_framework.routers import DefaultRouter
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from users.models import Author


app_name = "Content"

router = DefaultRouter()
router.register(r'NewsReport', NewsViewSet)


urlpatterns = [
    path('Content/homepage', homepage, name='homepage'),
    path('Content/success', success, name='success'),
    path('Content/about_BS', about_BS, name='about_BS'),
    path('Content/BS_delete_report', BSReportDeleteView.as_view(
        template_name='BS_delete_report.html'), name='BS_delete_report'),
    path('Content/ContactCreateView', ContactCreateView.as_view(
        template_name='contact_create.html'), name='contact_create'),
    path('Content/create_report', CreateReport.as_view(), name='create_report'),
    path('Content/report_list', report_list, name='report_list'),
    path("Content/<slug:slug>/", NewsReportDetailView.as_view,
         name="news_report_detail"),
    path('', include(router.urls)),
    path('Content/send_mail1', send_mail1, name='email'),
    path('Content/EditNewsReportView', EditNewsReportView.as_view(
        template_name='edit_report.html'), name='edit_report'),
    re_path('Content/<slug:slug>/', report_detail, name='report_detail'),
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Content/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Model
from users.models import Author
from datetime import datetime
from django.conf import settings
from rest_framework import serializers
from django.urls import reverse
from django.db.models.signals import pre_save, post_save, pre_delete
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from Complete_BS.utils import unique_slug_generator, unique_slug_generator1
from django.utils.text import slugify
from PIL import Image


class NewsReport(models.Model):
    headline = models.TextField(primary_key=True, max_length=100, default='')
    todaysDate = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, default='', blank=True)
    content = models.TextField(max_length=500, default='')
    photo = models.ImageField(upload_to='media/photo', blank=True)
    is_approved = models.BooleanField(default=True)
    slug = models.SlugField(max_length=100, null=True, blank=True, unique=True)

    def publish(self):
        self.todaysDate = datetime.now()
        self.save

    def get_absolute_url(self):
        return reverse('Content/report_detail,html',
                       kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        value = self.headline
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


"""
@receiver(pre_save, sender=NewsReport)
def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
"""


class LatestNews(models.Model):
    title = models.CharField(primary_key=True, max_length=100, default='')
    Date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(to=Author, on_delete=models.PROTECT, default='')
    content = models.TextField(max_length=500, default='')
    photo = models.ImageField(upload_to='media/photo', default='busgate.jpg')
    is_approved = models.BooleanField(default=True)
    slug = models.SlugField(max_length=100, null=True, blank=True, unique=True)

    def publish(self):
        self.Date = datetime.now()
        self.save()

    def __str__(self):
        return f'{self.title}'


@receiver(pre_save, sender=LatestNews)
def pre_save_receiver1(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator1(instance)


class ContactSubmission(models.Model):
    Date = models.DateField(auto_now_add=True)
    name = models.CharField(max_length=20, default='')
    email = models.EmailField(max_length=50, default='')
    subject = models.CharField(max_length=50, default='')
    message = models.TextField(max_length=300, default='')

    def __str__(self):
        return f'{self.Date} + {self.subject}'

    def publish(self):
        self.date = datetime.now()
        self.save()

Content/views.py
from django.http import HttpResponse, HttpResponseNotFound
from .models import NewsReport, ContactSubmission, LatestNews
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import ListView, DetailView
from django.views.generic import DeleteView, FormView
from django.template.loader import get_template
from django.template import Context
import requests
from django.core.mail import send_mail
from users.models import Author
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from .forms import NewsReportForm, ContactForm, EditNewsReportForm
from Complete_BS import settings
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.decorators.http import require_GET
from django.core.paginator import Paginator
from rest_framework import viewsets
from .serializers import NewsSerializer
# from django.core.files.storage import FileSystemStorage
import logging


def home(request):
    url = 'https://api.openweathermap.org/data/2.5/weather?q={},{}&units=metric&appid={}'
    cities = [('Sheffield', 'UK'), ('Melaka', 'Malaysia'), ('Bandung', 'Indonesia')]
    weather_data = []
    api_key = 'de13554a89154438878bf77424a0ca05'

    for city in cities:
        city_weather = requests.get(url.format(city[0], city[1], api_key)).json() # Request the API data and convert the JSON to Python data types

    weather = {
        'city': city_weather['name'] + ', ' + city_weather['sys']['country'],
        'temperature': city_weather['main']['temp'],
        'description': city_weather['weather'][0]['description']
    }
    weather_data.append(weather) # Add the data for the current city into our list

    return render(request, 'Content/home.html', {'title': 'Homepage', 'weather_data': weather_data})


def homepage(request):
    url = 'https://api.openweathermap.org/data/2.5/weather?q={},{}&units=metric&appid={}'
    cities = [('Sheffield', 'UK'), ('Melaka', 'Malaysia'), ('Bandung', 'Indonesia')]
    weather_data = []
    api_key = 'de13554a89154438878bf77424a0ca05'

    for city in cities:
        city_weather = requests.get(url.format(city[0], city[1], api_key)).json() # Request the API data and convert the JSON to Python data types

    weather = {
        'city': city_weather['name'] + ', ' + city_weather['sys']['country'],
        'temperature': city_weather['main']['temp'],
        'description': city_weather['weather'][0]['description']
    }
    weather_data.append(weather) # Add the data for the current city into our list

    return render(request, 'Content/homepage.html', {'title': 'Homepage', 'weather_data': weather_data})


@login_required
def report_list(request):
    reports = NewsReport.objects.all().order_by('todaysDate')
    context = {'reports': reports}
    return render(request, 'Content/list_news.html', context)


@login_required
def newsreport_detail(request, pk):
    report = get_object_or_404(NewsReport, pk=pk)
    if request.method != "POST":
        return HttpResponse("<h2>Method Not Allowed</h2>")
    else:
        NewsReport.headline = request.POST.get('headline')
        NewsReport.todaysDate = request.POST.get('todaysDate')
        NewsReport.content = request.POST.get('content')
        NewsReport.photo = request.POST.get('photo')
        NewsReport.slug = request.Post.get('slug')
        NewsReport.author = request.Post.get('author')
    return render(request, 'Content/report_detail', {'report': report})


class EditNewsReportView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = NewsReport
    fields = [
            'headline',
            'content',
            'photo',
            'is_approved',
            'author',
            'todaysDate',
            'slug',
            ]

    @login_required
    def edit_report(self, form, request):
        if request.method == 'POST':
            form = EditNewsReportForm(request.POST or None)
        if form.is_valid():
            form.save()  # Save the module to the database
            return redirect(request, 'homepage')  # Redirect to the module list page or any other page
        else:
            form = EditNewsReportForm()

        return render(request, 'Content/edit_report.html', {'form': form})


@login_required
def success(request):
    return render(request, 'Content/success.html')


class CreateReport(CreateView):
    # specify the model for create view
    model = NewsReport
    # specify the fields to be displayed
    fields = ['headline', 'content']
    template_name = 'Content/create_report.html'
    success_url = 'homepage'



def about_BS(request):
    return render(request, 'Content/about_BS.html',
                  {'title': 'Start Learning About BS News'})


def policies(request):
    return render(request, 'Content/policies.html',
                  {'title': 'BS News Offical Reporting Policies'})


class BSReportUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = NewsReport
    fields = ['headline', 'content', 'photo', 'is_approved', 'author', 'todaysDate', 'slug']
    success_url = 'homepage'
    template_name = 'Content/create_news_report.html'

    @login_required
    def test_func2(self):
        newsreport = self.get_object()
        return self.request.username == newsreport.author


class BSReportDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = NewsReport
    form_class = NewsReportForm
    success_url = 'homepage'

    @login_required
    def test_func3(self):
        newsreport = self.get_object()
        return self.request.username == newsreport.author


class ContactCreateView(CreateView, FormView):
    model = ContactSubmission
    form = ContactForm
    success_url = 'success'
    template_name = 'Content/contact_create.html'
    context = {'form': form}

    @login_required
    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'Unable to send the enquiry')
        return super().form_invalid(form)

    @login_required
    def get_success_url(self):
        return (self.request.path, 'success')


@login_required
class LatestNewsCreateView(CreateView, FormView):
    model = LatestNews
    form = NewsReportForm
    success_url = 'success'
    template_name = 'Content/create_report.html'

    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'Unable to send the enquiry')
        return super().form_invalid(form)

    @login_required
    def get_success_url(self):
        return (self.request.path, 'success')


@login_required
def send_mail1(request):
    context = {}

    if request.method == 'POST':
        address = request.POST.get('address')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        if address and subject and message:
            try:
                send_mail1(subject, message, settings.EMAIL_HOST_USER,
                           [address])
                context['result'] = 'Email sent successfully'
            except Exception as e:
                context['result'] = f'Error sending email: {e}'
        else:
            context['result'] = 'All fields are required'

    return render(request, "email.html", context)


@login_required
def report_detail(request, slug):
    # Filter posts based on the slug (case-insensitive)
    q = NewsReport.objects.filter(slug__iexact=slug)

    if q.exists():
            # If a post with the given slug exists, retrieve the first
            # matching post
        q = q.first()
    else:
        # If no post is found, return an "Post Not Found" response
        return HttpResponse('<h1>Post Not Found</h1>')

    # Create a context dictionary containing the retrieved post
    context = {'NewsReport': q}

    # Render the 'details.html' template with the context
    return render(request, 'Content/news_report_detail.html', context)


class NewsViewSet(viewsets.ModelViewSet):
    queryset = NewsReport.objects.all()
    serializer_class = NewsSerializer


class NewsReportDetailView(DetailView):
    model = NewsReport
    template_name = 'report_detail.html'
    context_object_name = 'report'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    @login_required
    def get_object(self, queryset=None):
        slug = self.kwargs.get(self.slug_url_kwarg)
        queryset = queryset or self.get_queryset()
        return get_object_or_404(queryset, **{self.slug_field: slug})


"""
logger = logging.getLogger(__name__)


def my_view(request):
    logger.debug("This is a debug message")
    logger.info("This is an info message")
    logger.warning("This is a warning message")
    logger.error("This is an error message")
"""

Content/templates/Content/Base.html
<!DOCTYPE html>
{% load static %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}
{% endif %}
<html>
<head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
crossorigin="anonymous">
<link rel="stylesheet" href="static/style.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> <!-- Compiled and minified JavaScript --> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> 
</head>
<body class="bg-primary-subtle">
    <br>
    <br>
    <br>
<header class="site-header">
<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top text-bg-primary p-3">
<div class="container">
<a class="navbar-brand mr-4 link-body-emphasis" href="{% url 'Content:homepage' %}"><title>{{title}}</title></a>
<ul class="navbar-lists">
    <li><a class="navbar-link alert-link" href="{% url 'Content:homepage'%}">Home Page</a></li>
    <li><a class="navbar-link alert-link"  href="{% url 'Content:about_BS'%}">About BS Content</a></li>
    <li><a class="navbar-link alert-link" href="{% url 'Content:report_list'%}">List of The Latest BS Content</a></li>
    <li><a class="navbar-link alert-link" href="{% url 'Content:contact_create'%}">Contact IT Admin </a></li>
    <li><a class="navbar-link alert-link" href="">Latest News Live Feed</a></li>
    {% if user.is_authenticated %}
    <li><a class="navbar-link alert-link" href="{% url 'Content:create_report' %}">Create BS News Reports</a></li>
    <form method="post" id="frm_logout" action="{% url 'logout'%}" style="display:inline;">
    {% csrf_token %}
    <li><button type="submit" class="navbar-link alert-link" style="background:none; border:none; cursor:pointer;">Logout</button></li>
    </form>
    {% else %}
    <li><a class="nav-item nav-link alert-link" href="{% url 'login' %}">Login</a></li>
    <li><a class="nav-item nav-link alert-link" href="{% url 'register' %}">Register</a></li>
    <li><a class="nav-item nav-link alert-link" href="{% url 'register' %}">Update Profile</a></li>
    {% endif %}
    <li><label class="switch"><input type="checkbox" id="darkModeToggle"><span class="slider round"></span></label></li>
</ul>
</nav>
</div>
</header>
<br>
<br>
<br>
<br>
<div class="row justify-content-center">
<button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">click for weather</button>
</div>
<div class="row justify-content-center">
<div class="content-section">
<div class="container">
{% block content %}{% endblock %}
</div>
</div>
</div>
<div class="row justify-content-right">
<div class="content-section">
<div class="container">
{% block sidebar %}
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasRightLabel">International Weather Forecast</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body"> 
<h3>Current Weather</h3> 
    <p class='text-muted'>Cities across United Kingdom 
        <ul class="list-group"> 
        {% for weather in weather_data %} 
            <li class="list-group-item list-group-item-light">{{ weather.city }}: {{ weather.description }}, {{ weather.temperature }}&deg;C</li> 
        {% endfor %} 
        </ul> 
    </p> 
</div> 
  </div>
</div>



{% endblock %}
</div>
</div>
</div>
<br>
<br>
<br>
<br>
<br>
<nav class="navbar navbar-expand-lg fixed-bottom bg-body-tertiary">
<div class="container-fluid alert alert-info" role="alert">
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item"><a class="alert-link" aria-current="page" href="{% url 'Content:report_list'%}">Latest BS News Reported Online</a></li>
    <li class="nav-item"><a class="alert-link" aria-current="page" href="{% url 'policies'%}">BS News Publishing Policies</a></li>
    <li class="nav-item"><a class="alert-link" aria-current="page" href="{% url 'Content:about_BS' %}">About BS Content</a></li>
    <li class="nav-item"><a class="alert-link" aria-current="page" href="{% url 'Content:contact_create' %}">Contact Page</a></li>
    <li class="nav-item"><a class="alert-link" aria-current="page" href="">How to Create BS</a></li>
    <li><label class="switch"><input type="checkbox" id="darkModeToggle"><span class="slider round"></span></label></li>
    </div>
</ul>
</div>
</nav>
</div>
<footer>
    <p>&copy; 2025, Cuthbert Baines.
            All rights reserved.</p>
</footer>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
crossorigin="anonymous"></script>
<script src="script.js"></script>
</body>
</html>

Content/templates/Content/Base1.html
<!DOCTYPE html>
{% load static %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}
{% endif %}
<html>
<head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> <!-- Compiled and minified JavaScript --> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> 
<title>Complete BS Content Online {{title}}</title>
</head>
<body>
<div class="container">
<header class="site-header">
<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
<div class="container">
<a class="navbar-brand mr-4" href="{% url 'homepage' %}">BS Content Services for Creatives</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarToggle">
<div class="navbar-nav mr-auto">
<a class="nav-item nav-link" href="{% url 'homepage'%}">Home Page</a>
<a class="nav-item nav-link" href="{% url 'about_BS'%}">About BS Content</a>
<a class="nav-item nav-link" href="{% url 'report'%}">Latest BS Content</a>
<a class="nav-item nav-link" href="{% url 'contact'%}">Contact Page</a>
<a class="nav-item nav-link" href="{% url 'BS_News/Frontpage'%}">Latest News Report Frontpage Feed</a>
</div>
<!-- Navbar Right Side -->
<div class="navbar-nav">
    {% if user.is_authenticated %}
    <a class="nav-item nav-link" href="{% url 'BS_Content:issue_create'%}">Create New BS News Report</a>
    <form method="post" id="frm_logout" action="{% url 'logout'%}"
    style="display:inline;">
    {% csrf_token %}
    <button type="submit" class="nav-item nav-link"
    style="background:none; border:none; cursor:pointer;">Logout</button>
    </form>
    {% else %}
    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
    <a class="nav-item nav-link" href="{% url 'profile' %}">Update Profile</a>
    {% endif %}
    </div>
</div>
</div>
</nav>
</header>
<div class="row">
<div class="col-md-8">
{% block content %}{% endblock %}
</div>
{% block sidebar %}{% endblock %}
<div class="col-md-4">
<div class="content-section">
<h3>The Latest Upto date BS Online Content</h3>
<p class='text-muted'>This web-app is where people can transform their lives from being a passive submissive recepticle into an active creative producer of news, events and current affairs
 and contributors can submit their BS News articles, submit your content here and when it's approved by the BS IT Administrator.
<ul class="list-group">
<li class="list-group-item list-group-item-light"><a href="{% url 'Latest_BS_content' %}">Latest BS News Reported Online</a></li>
<li class="list-group-item list-group-item-light"> <a href="{% url 'policies' %}">BS News Publishing Policies</a></li>
<li class="list-group-item list-group-item-light"><a href="{% url 'about' %}">About BS Content</a></li>
<li class="list-group-item list-group-item-light"><a href="{% url 'contact' %}">Contact Page</a></li>
<li class="list-group-item list-group-item-light"><a href="{% url '' %}"></a></li>
<li class="list-group-item list-group-item-light"><a href="{% url '' %}"></a></li>
<li class="list-group-item list-group-item-light"><a href="{% url '' %}"></a></li>
</ul>
</p>
</div>
</div>
</div>
</div>
</html>

Content/templates/Content/Email.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
        <style>
            @import url('https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900');
        </style>
    </head>
    <body style="background: #f5f8fa;font-family: 'Roboto', sans-serif;">
        <div style="width: 90%;max-width:600px;margin: 20px auto;background: #ffffff;">
            <section style="margin: 0 15px;color:#425b76;">
                <h2 style="margin: 40px 0 27px 0;text-align: center;">Thank you to registration</h2>
                <hr style="border:0;border-top: 1px solid rgba(66,91,118,0.3);max-width: 50%">
                <p style="font-size:15.5px;font-weight: bold;margin:40px 20px 15px 20px;">Hi {{username}}, we have received your details and will process soon.</p>
            </section>
        </div>
    </body>
</html>

Content/templates/Content/contact.html
{% extends "Content/Base.html" %}
{% block content %}
<body>
    <div class="container">
        <h1>Contact The On call IT Administrator of BS Content</h1>
        <form method="post" action="{% url 'contact' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Name:</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="id_email">Email:</label>
                {{ form.email }}
            </div>
            <div class="form-group">
                <label for="id_subject">Subject:</label>
                {{ form.subject }}
            </div>
            <div class="form-group">
                <label for="id_message">Message:</label>
                {{ form.message }}
            </div>
            <div class="form-group">
                <button type="submit">Send</button>
            </div>
        </form>
    </div>
</body>
{% endblock content %}

Content/templates/Content/edit_report.html
{% extends "Content/Base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if title %}
    <h4>{{ edit_report }}</h4>
    {% endif %}
    <div class="content-section">
        <form action="" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
            {% crispy form.as_p %}
            <button type="submit" class="btn btn-secondary">Submit</button>
            </fieldset>
        </form>
    </div>
{% endblock content %}

Content/templates/Content/home.html
{% extends "Content/Base.html" %}
{% block content %}
<br>
<br>
<h3 class="text-primary-emphasis row justify-content-center">The Latest BS News Content on Demand</h3>

<p class='text-muted text-primary-emphasis row justify-content-center'>
    This web-app is where creatives and contributors can access theit own on demand news  
   service here at Breaking Sheffield's News Online, just submit your report here and when 
   it's approved by the BS IT Administrator it will appear on the public web site.
</p>

{% endblock %}